/**
 * @project IEC61850 simulator
 * @date 10.03.2020
 * @path serverguiiec61850.gui.Gui.java
 * @author Philipp Mandl
 */
package serverguiiec61850.gui;

import com.beanit.openiec61850.SclParseException;
import com.beanit.openiec61850.ServiceError;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.ConnectException;
import java.net.MalformedURLException;
import java.net.SocketException;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;
import serverguiiec61850.network.Client;
import serverguiiec61850.network.Server;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import serverguiiec61850.files.ModifyXmlFile;
import serverguiiec61850.network.NetworkUtil;

/**
 * main window
 *
 */
public class Gui extends javax.swing.JFrame {

    /**
     * logger in class Gui
     */
    public static final Logger LOGGER_GUI = LoggerFactory.getLogger(Gui.class);

    /**
     * path where the modified xml is
     */
    public static String iedPath = System.getProperty("user.dir") + "\\files\\icd\\everyIed.xml";

    private Server server;
    private Client client;
    ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();

    /**
     * simulator enable state
     */
    public static boolean enabled = true;

    HelpWindow help = null;

    ModifyXmlFile xml = null;
    private String ied;

    /**
     * creates new form gui
     */
    public Gui() {
        super("IEC61850 Simulator");

        try {
            // Set System L&F
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            LOGGER_GUI.error("look and feel not avaible", e);
        }
        initComponents();
        ImageIcon img = new ImageIcon(System.getProperty("user.dir") + "\\files\\icon.png");
        this.setIconImage(img.getImage());
        createNetDeviceList();
        JTextAreaAppender masterappender = new JTextAreaAppender(masterLogTP, simLogTP, reportDatasetTP);
        iedPathTB.setText(System.getProperty("user.dir") + "\\files\\example.icd");
        //KeyListenerGui keyListenerGui = new KeyListenerGui();
        reserveReportRBActionPerformed(null);
        reserveReportRB.setSelected(true);
//        createDatasetRBActionPerformed(null);
//        createDatasetRB.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor(upps).
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datasetBG = new javax.swing.ButtonGroup();
        reportBG = new javax.swing.ButtonGroup();
        mainFrame = new javax.swing.JTabbedPane();
        connectTAB = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        iedPathTB = new javax.swing.JTextField();
        icodersclLBL = new javax.swing.JLabel();
        selectFileBTN = new javax.swing.JButton();
        selectedIedLBL = new javax.swing.JLabel();
        IedLBL = new javax.swing.JLabel();
        changeIedBTN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        netDevicesTA = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        netInfosTA = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        connectedLBL = new javax.swing.JLabel();
        startBTN = new javax.swing.JButton();
        stopBTN = new javax.swing.JButton();
        portTB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ipTB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        createServer = new javax.swing.JCheckBox();
        changeIedTAB = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        reportDatasetTP = new javax.swing.JTextPane();
        changeValuesBTN = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        reportPNL = new javax.swing.JPanel();
        selectReferenceReportBTN = new javax.swing.JButton();
        reportStartBTN = new javax.swing.JButton();
        valueReportPNL = new javax.swing.JPanel();
        valueLBL = new javax.swing.JLabel();
        valueTB = new javax.swing.JTextField();
        referenceReportPNL = new javax.swing.JPanel();
        referenceLBL = new javax.swing.JLabel();
        referenceTB = new javax.swing.JTextField();
        reserveTimeReportPNL = new javax.swing.JPanel();
        reserveTimeLBL = new javax.swing.JLabel();
        reserveTimeTB = new javax.swing.JTextField();
        triggerOptionsReportPNL = new javax.swing.JPanel();
        triggerOptionsLBL = new javax.swing.JLabel();
        triggerOptionsTB = new javax.swing.JTextField();
        IntegrityReportPNL = new javax.swing.JPanel();
        IntegrityLBL = new javax.swing.JLabel();
        integrityPeriodTB = new javax.swing.JTextField();
        radioButtonsReportPNL = new javax.swing.JPanel();
        cancelReservationRB = new javax.swing.JRadioButton();
        setIntegrityReportRB = new javax.swing.JRadioButton();
        setTriggerReportRB = new javax.swing.JRadioButton();
        sendGeneralInterrogationReportRB = new javax.swing.JRadioButton();
        setDatasetReportRB = new javax.swing.JRadioButton();
        disableReportRB = new javax.swing.JRadioButton();
        enableReportRB = new javax.swing.JRadioButton();
        reserveReportRB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        simulateTAB = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        saveCsvBTN = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        simLogTP = new javax.swing.JTextPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        simulateRampFromTB = new javax.swing.JTextField();
        simulateRampStartBTN = new javax.swing.JButton();
        simulateRampToTB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        simulateRampTimeTB = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        simulateRampReferenceTB = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        simulateRampFcCB = new javax.swing.JComboBox<>();
        simulateRampStepsTB = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        selectReferenceRampBTN = new javax.swing.JButton();
        simulateRampStopBTN = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        simulatePulsMinTB = new javax.swing.JTextField();
        simulatePulsMaxTB = new javax.swing.JTextField();
        simulatePulsTimeOffTB = new javax.swing.JTextField();
        simulatePulsTimeOnTB = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        simulatePulsStartBTN = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        simulatePulsReferenceTB = new javax.swing.JTextField();
        simulatePulsFcCB = new javax.swing.JComboBox<>();
        simulatePulsStopBTN = new javax.swing.JButton();
        selectReferencePulsBTN = new javax.swing.JButton();
        logTAB = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        masterLogTP = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setMinimumSize(new java.awt.Dimension(200, 200));

        jSplitPane3.setBorder(null);

        iedPathTB.setText("F:\\diplomarbeit\\project\\openiec61850Simulator\\serverguiiec61850\\src\\main\\java\\serverguiiec61850\\files");

        icodersclLBL.setText("ICD oder SCL file");

        selectFileBTN.setText("select file");
        selectFileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileBTNActionPerformed(evt);
            }
        });

        selectedIedLBL.setText("selected IED: ");

        IedLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IedLBL.setText("select IED");

        changeIedBTN.setText("change");
        changeIedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeIedBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(selectedIedLBL)
                                .addGap(44, 44, 44)
                                .addComponent(IedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(changeIedBTN)
                                .addGap(160, 160, 160))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(iedPathTB, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(selectFileBTN))
                    .addComponent(icodersclLBL))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icodersclLBL)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iedPathTB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeIedBTN)
                    .addComponent(selectedIedLBL))
                .addContainerGap(531, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(jPanel3);

        netDevicesTA.setEditable(false);
        netDevicesTA.setColumns(20);
        netDevicesTA.setRows(5);
        netDevicesTA.setText("found no devices");
        jScrollPane5.setViewportView(netDevicesTA);

        jLabel9.setText("Network Devices:");

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        netInfosTA.setEditable(false);
        netInfosTA.setColumns(20);
        netInfosTA.setRows(5);
        netInfosTA.setText("IP: 0.0.0.0\nIP-SUBNET: 0.0.0.0\nIP-GATEWAY: 0.0.0.0");
        jScrollPane2.setViewportView(netInfosTA);

        jLabel15.setText("address settings in file:");

        connectedLBL.setText("not connected");

        startBTN.setText("start");
        startBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBTNActionPerformed(evt);
            }
        });

        stopBTN.setText("stop");
        stopBTN.setEnabled(false);
        stopBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBTNActionPerformed(evt);
            }
        });

        portTB.setText("102");

        jLabel6.setText(":");

        ipTB.setText("127.0.0.1");

        jLabel1.setText("ip");

        jLabel5.setText("port");

        jLabel10.setText("connect to:");

        createServer.setSelected(true);
        createServer.setText("create server");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(connectedLBL)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(ipTB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(portTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(startBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stopBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(createServer))))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(156, 156, 156))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(124, 124, 124)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBTN)
                    .addComponent(stopBTN)
                    .addComponent(createServer))
                .addGap(18, 18, 18)
                .addComponent(connectedLBL)
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );

        jSplitPane3.setRightComponent(jPanel4);

        javax.swing.GroupLayout connectTABLayout = new javax.swing.GroupLayout(connectTAB);
        connectTAB.setLayout(connectTABLayout);
        connectTABLayout.setHorizontalGroup(
            connectTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectTABLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane3)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        connectTABLayout.setVerticalGroup(
            connectTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectTABLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSplitPane3)
                .addGap(35, 35, 35))
        );

        mainFrame.addTab("connect", connectTAB);

        jSplitPane2.setBorder(null);
        jSplitPane2.setForeground(new java.awt.Color(255, 255, 255));

        reportDatasetTP.setEditable(false);
        jScrollPane6.setViewportView(reportDatasetTP);

        changeValuesBTN.setText("change server manual");
        changeValuesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeValuesBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(changeValuesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeValuesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel5);

        selectReferenceReportBTN.setText("select Reference");
        selectReferenceReportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectReferenceReportBTNActionPerformed(evt);
            }
        });

        reportStartBTN.setText("do");
        reportStartBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportStartBTNActionPerformed(evt);
            }
        });

        valueReportPNL.setPreferredSize(new java.awt.Dimension(120, 30));

        valueLBL.setText("value:");

        valueTB.setText("value");

        javax.swing.GroupLayout valueReportPNLLayout = new javax.swing.GroupLayout(valueReportPNL);
        valueReportPNL.setLayout(valueReportPNLLayout);
        valueReportPNLLayout.setHorizontalGroup(
            valueReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valueReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valueLBL)
                .addGap(42, 42, 42)
                .addComponent(valueTB, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        valueReportPNLLayout.setVerticalGroup(
            valueReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valueReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valueReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLBL)
                    .addComponent(valueTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        referenceReportPNL.setPreferredSize(new java.awt.Dimension(139, 30));

        referenceLBL.setText("reference:");

        referenceTB.setText("IED1/LogicalNode.underLN.value");

        javax.swing.GroupLayout referenceReportPNLLayout = new javax.swing.GroupLayout(referenceReportPNL);
        referenceReportPNL.setLayout(referenceReportPNLLayout);
        referenceReportPNLLayout.setHorizontalGroup(
            referenceReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referenceReportPNLLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(referenceLBL)
                .addGap(36, 36, 36)
                .addComponent(referenceTB, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        referenceReportPNLLayout.setVerticalGroup(
            referenceReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referenceReportPNLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(referenceReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceLBL)
                    .addComponent(referenceTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        reserveTimeReportPNL.setPreferredSize(new java.awt.Dimension(135, 30));
        reserveTimeReportPNL.setVerifyInputWhenFocusTarget(false);

        reserveTimeLBL.setText("reserve time:");

        reserveTimeTB.setText("5");

        javax.swing.GroupLayout reserveTimeReportPNLLayout = new javax.swing.GroupLayout(reserveTimeReportPNL);
        reserveTimeReportPNL.setLayout(reserveTimeReportPNLLayout);
        reserveTimeReportPNLLayout.setHorizontalGroup(
            reserveTimeReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTimeReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reserveTimeLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(reserveTimeTB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        reserveTimeReportPNLLayout.setVerticalGroup(
            reserveTimeReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTimeReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reserveTimeReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveTimeLBL)
                    .addComponent(reserveTimeTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        triggerOptionsLBL.setText("trigger options:");

        triggerOptionsTB.setText("trigger");

        javax.swing.GroupLayout triggerOptionsReportPNLLayout = new javax.swing.GroupLayout(triggerOptionsReportPNL);
        triggerOptionsReportPNL.setLayout(triggerOptionsReportPNLLayout);
        triggerOptionsReportPNLLayout.setHorizontalGroup(
            triggerOptionsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(triggerOptionsReportPNLLayout.createSequentialGroup()
                .addComponent(triggerOptionsLBL)
                .addGap(39, 39, 39)
                .addComponent(triggerOptionsTB, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        triggerOptionsReportPNLLayout.setVerticalGroup(
            triggerOptionsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(triggerOptionsReportPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(triggerOptionsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(triggerOptionsLBL)
                    .addComponent(triggerOptionsTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        IntegrityReportPNL.setPreferredSize(new java.awt.Dimension(172, 30));

        IntegrityLBL.setText("integrityPeriod:");

        javax.swing.GroupLayout IntegrityReportPNLLayout = new javax.swing.GroupLayout(IntegrityReportPNL);
        IntegrityReportPNL.setLayout(IntegrityReportPNLLayout);
        IntegrityReportPNLLayout.setHorizontalGroup(
            IntegrityReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntegrityReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IntegrityLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(integrityPeriodTB, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        IntegrityReportPNLLayout.setVerticalGroup(
            IntegrityReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntegrityReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(integrityPeriodTB)
                .addComponent(IntegrityLBL))
        );

        reportBG.add(cancelReservationRB);
        cancelReservationRB.setText("cancel reservation");
        cancelReservationRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationRBActionPerformed(evt);
            }
        });

        reportBG.add(setIntegrityReportRB);
        setIntegrityReportRB.setText("set integrity");
        setIntegrityReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setIntegrityReportRBActionPerformed(evt);
            }
        });

        reportBG.add(setTriggerReportRB);
        setTriggerReportRB.setText("set trigger");
        setTriggerReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTriggerReportRBActionPerformed(evt);
            }
        });

        reportBG.add(sendGeneralInterrogationReportRB);
        sendGeneralInterrogationReportRB.setText("send generell interrogation");
        sendGeneralInterrogationReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendGeneralInterrogationReportRBActionPerformed(evt);
            }
        });

        reportBG.add(setDatasetReportRB);
        setDatasetReportRB.setText("set dataset");
        setDatasetReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDatasetReportRBActionPerformed(evt);
            }
        });

        reportBG.add(disableReportRB);
        disableReportRB.setText("disable report");
        disableReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableReportRBActionPerformed(evt);
            }
        });

        reportBG.add(enableReportRB);
        enableReportRB.setText("enable report");
        enableReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableReportRBActionPerformed(evt);
            }
        });

        reportBG.add(reserveReportRB);
        reserveReportRB.setText("reserve Report (in log)");
        reserveReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveReportRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioButtonsReportPNLLayout = new javax.swing.GroupLayout(radioButtonsReportPNL);
        radioButtonsReportPNL.setLayout(radioButtonsReportPNLLayout);
        radioButtonsReportPNLLayout.setHorizontalGroup(
            radioButtonsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonsReportPNLLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(radioButtonsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveReportRB)
                    .addComponent(cancelReservationRB)
                    .addComponent(setIntegrityReportRB)
                    .addComponent(setDatasetReportRB)
                    .addComponent(sendGeneralInterrogationReportRB)
                    .addGroup(radioButtonsReportPNLLayout.createSequentialGroup()
                        .addComponent(disableReportRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enableReportRB))
                    .addComponent(setTriggerReportRB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        radioButtonsReportPNLLayout.setVerticalGroup(
            radioButtonsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonsReportPNLLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(reserveReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelReservationRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setIntegrityReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setTriggerReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendGeneralInterrogationReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setDatasetReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(radioButtonsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disableReportRB)
                    .addComponent(enableReportRB))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel4.setText("functions:");

        javax.swing.GroupLayout reportPNLLayout = new javax.swing.GroupLayout(reportPNL);
        reportPNL.setLayout(reportPNLLayout);
        reportPNLLayout.setHorizontalGroup(
            reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPNLLayout.createSequentialGroup()
                .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPNLLayout.createSequentialGroup()
                        .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reportPNLLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4))
                            .addGroup(reportPNLLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(radioButtonsReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(reportPNLLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(IntegrityReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(reportPNLLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(referenceReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valueReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectReferenceReportBTN))
                                    .addGroup(reportPNLLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(triggerOptionsReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(reserveTimeReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 219, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reportStartBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        reportPNLLayout.setVerticalGroup(
            reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPNLLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonsReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reportPNLLayout.createSequentialGroup()
                        .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referenceReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectReferenceReportBTN))
                        .addGap(18, 18, 18)
                        .addComponent(IntegrityReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triggerOptionsReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reserveTimeReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addComponent(reportStartBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("report", reportPNL);

        jSplitPane2.setRightComponent(jTabbedPane4);
        jTabbedPane4.getAccessibleContext().setAccessibleName("report CONTROL");

        javax.swing.GroupLayout changeIedTABLayout = new javax.swing.GroupLayout(changeIedTAB);
        changeIedTAB.setLayout(changeIedTABLayout);
        changeIedTABLayout.setHorizontalGroup(
            changeIedTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeIedTABLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );
        changeIedTABLayout.setVerticalGroup(
            changeIedTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeIedTABLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );

        mainFrame.addTab("change IED", changeIedTAB);

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(300);

        jLabel3.setText("Values changed by simulator:");

        saveCsvBTN.setText("save .csv");
        saveCsvBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCsvBTNActionPerformed(evt);
            }
        });

        simLogTP.setEditable(false);
        jScrollPane3.setViewportView(simLogTP);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(saveCsvBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(saveCsvBTN)
                .addGap(13, 13, 13))
        );

        jSplitPane1.setRightComponent(jPanel7);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        simulateRampFromTB.setText("0");

        simulateRampStartBTN.setText("start");
        simulateRampStartBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateRampStartBTNActionPerformed(evt);
            }
        });

        simulateRampToTB.setText("100");

        jLabel7.setText("from");

        jLabel8.setText("to");

        simulateRampTimeTB.setText("10000");

        jLabel20.setText("time ms");

        simulateRampReferenceTB.setText("IED1/LogicalNode.underLN.value");

        jLabel21.setText("Reference");

        jLabel22.setText("FC");

        simulateRampFcCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ST","MX","SP","SV","CF","DC","SG","SE","SR","OR","BL","EX","CO","US","MS","RP","BR","LG", "GO", "GS","ALL","NONE" }));

        simulateRampStepsTB.setText("100");

        jLabel25.setText("steps");

        selectReferenceRampBTN.setText("select reference");
        selectReferenceRampBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectReferenceRampBTNActionPerformed(evt);
            }
        });

        simulateRampStopBTN.setText("stop");
        simulateRampStopBTN.setEnabled(false);
        simulateRampStopBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateRampStopBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simulateRampReferenceTB, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(simulateRampFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectReferenceRampBTN)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7)
                                        .addComponent(simulateRampTimeTB)
                                        .addComponent(jLabel20)
                                        .addComponent(simulateRampFromTB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(simulateRampStartBTN))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(simulateRampStopBTN)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel25)
                                        .addComponent(simulateRampStepsTB)
                                        .addComponent(jLabel8)
                                        .addComponent(simulateRampToTB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(simulateRampReferenceTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(simulateRampFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(selectReferenceRampBTN)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulateRampFromTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulateRampToTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulateRampTimeTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulateRampStepsTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulateRampStartBTN)
                    .addComponent(simulateRampStopBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ramp", jPanel2);

        simulatePulsMinTB.setText("0");

        simulatePulsMaxTB.setText("10");

        simulatePulsTimeOffTB.setText("1");

        simulatePulsTimeOnTB.setText("2000");

        jLabel16.setText("min");

        jLabel17.setText("max");

        jLabel18.setText("time off ms");

        jLabel19.setText("time on ms");

        simulatePulsStartBTN.setText("start");
        simulatePulsStartBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulatePulsStartBTNActionPerformed(evt);
            }
        });

        jLabel23.setText("Reference");

        jLabel24.setText("FC");

        simulatePulsReferenceTB.setText("IED1/LogicalNode.underLN.value");

        simulatePulsFcCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ST","MX","SP","SV","CF","DC","SG","SE","SR","OR","BL","EX","CO","US","MS","RP","BR","LG", "GO", "GS","ALL","NONE" }));

        simulatePulsStopBTN.setText("stop");
        simulatePulsStopBTN.setEnabled(false);
        simulatePulsStopBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulatePulsStopBTNActionPerformed(evt);
            }
        });

        selectReferencePulsBTN.setText("select reference");
        selectReferencePulsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectReferencePulsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(simulatePulsFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 137, Short.MAX_VALUE))
                            .addComponent(simulatePulsReferenceTB)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel23))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectReferencePulsBTN)
                                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(simulatePulsStartBTN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(simulatePulsTimeOffTB, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel18)
                                                .addComponent(simulatePulsMinTB, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(60, 60, 60)
                                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel17)
                                                .addComponent(simulatePulsTimeOnTB, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(simulatePulsMaxTB, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addComponent(simulatePulsStopBTN)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(simulatePulsReferenceTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(simulatePulsFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(selectReferencePulsBTN)
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulatePulsMinTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulatePulsMaxTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulatePulsTimeOffTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulatePulsTimeOnTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulatePulsStartBTN)
                    .addComponent(simulatePulsStopBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("puls", jPanel12);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(jPanel8);

        javax.swing.GroupLayout simulateTABLayout = new javax.swing.GroupLayout(simulateTAB);
        simulateTAB.setLayout(simulateTABLayout);
        simulateTABLayout.setHorizontalGroup(
            simulateTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        simulateTABLayout.setVerticalGroup(
            simulateTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulateTABLayout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainFrame.addTab("simulate", simulateTAB);

        jLabel26.setText("log:");

        masterLogTP.setEditable(false);
        jScrollPane4.setViewportView(masterLogTP);

        javax.swing.GroupLayout logTABLayout = new javax.swing.GroupLayout(logTAB);
        logTAB.setLayout(logTABLayout);
        logTABLayout.setHorizontalGroup(
            logTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTABLayout.createSequentialGroup()
                .addGroup(logTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logTABLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel26))
                    .addGroup(logTABLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
        );
        logTABLayout.setVerticalGroup(
            logTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTABLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );

        mainFrame.addTab("log", logTAB);

        jMenu1.setText("Help");

        jMenuItem1.setText("internal help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenuItem1.getAccessibleContext().setAccessibleName("help");

        jMenuItem3.setLabel("open github repository");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainFrame.setEnabledAt(1, false);
        mainFrame.setEnabledAt(2, false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeValuesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeValuesBTNActionPerformed
//        Thread clientGui = new Thread() {
//            public void run() {
        try {
            GuiTree changevalues = new GuiTree(xml, ied);
            LOGGER_GUI.info("change values manual \n");
        } catch (UnknownHostException e) {
            LOGGER_GUI.error("unknmown host", e);
        } catch (NullPointerException e) {
            LOGGER_GUI.error("error", e);
        } catch (ServiceError e) {
            LOGGER_GUI.error("error", e);
        } catch (IOException e) {
            LOGGER_GUI.error("error", e);
        }
//            }
//        };
//        clientGui.start();

    }//GEN-LAST:event_changeValuesBTNActionPerformed

    private void changeIedBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeIedBTNActionPerformed
        // JFileChooser-Objekt erstellen
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(System.getProperty("user.dir") + "\\files\\icd\\"));
        // Dialog zum Oeffnen von Dateien anzeigen
        int rueckgabeWert = chooser.showDialog(this, "select IED");
        String iedPathName = "no IED selected";
        if (rueckgabeWert == JFileChooser.APPROVE_OPTION) {
            iedPath = chooser.getSelectedFile().getPath();
            iedPathName = chooser.getSelectedFile().getName();
        }

        netInfosTA.setText(null);
        try {
//            iedPathName = iedPathName.substring(0, iedPathName.lastIndexOf("."));
            createNetInfoList(iedPathName);
//        } catch (StringIndexOutOfBoundsException e) {
//            LOGGER_GUI.error("more than one . in filename is not permitted", e);
        } catch (NullPointerException e) {
            LOGGER_GUI.error("no addressblock found", e);
        }
        IedLBL.setText(iedPathName);
        this.ied = IedLBL.getText();
        LOGGER_GUI.info("changed IED " + iedPathName + "\n");
    }//GEN-LAST:event_changeIedBTNActionPerformed

    private void selectFileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileBTNActionPerformed

        // JFileChooser-Objekt erstellen
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(iedPathTB.getText()).getParentFile());
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("scd,scl,icd,xml files (*.scd,*.scl,*.icd,*.xml)", "scd", "scl", "icd", "xml");
        chooser.setFileFilter(filter);

        int rueckgabeWert = chooser.showDialog(this, "select a SCD/ICD file");

        if (rueckgabeWert == JFileChooser.APPROVE_OPTION) {
            LOGGER_GUI.info("The path of the file is: " + chooser.getSelectedFile().getPath());
            iedPathTB.setText(chooser.getSelectedFile().getPath());
            LOGGER_GUI.info("changed SCD/ICD file, new file: " + chooser.getSelectedFile().getName() + "\n");
        }

        File dir = new File(iedPath).getParentFile();
        if (dir.isDirectory()) {
            String[] entries = dir.list();
            for (String entrie : entries) {
                File aktFile = new File(dir.getPath(), entrie);
                aktFile.delete();
            }
        }

        xml = new ModifyXmlFile(iedPathTB.getText());
        try {
            xml.splitIed();
        } catch (TransformerException e) {
            LOGGER_GUI.error("error", e);
        } catch (IOException e) {
            LOGGER_GUI.error("error", e);
        } catch (SAXException e) {
            LOGGER_GUI.error("error", e);
        } catch (ParserConfigurationException e) {
            LOGGER_GUI.error("error", e);
        }
        changeIedBTNActionPerformed(null);
    }//GEN-LAST:event_selectFileBTNActionPerformed

    private void stopBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBTNActionPerformed
        //stop button in connect
        try {
            client.quit();
            try {
                server.quit();
            } catch (NullPointerException e) {

            }

            startBTN.setEnabled(true);
            stopBTN.setEnabled(false);
            selectFileBTN.setEnabled(true);
            changeIedBTN.setEnabled(true);
            mainFrame.setEnabledAt(1, false);
            mainFrame.setEnabledAt(2, false);
            connectedLBL.setText("server stopped");
            connectedLBL.setForeground(Color.black);

            LOGGER_GUI.info("\n server stopped\n");
        } catch (Exception e) {
            connectedLBL.setText("error");
            connectedLBL.setForeground(Color.red);

            LOGGER_GUI.error("error while closing server and client", e);
        }
    }//GEN-LAST:event_stopBTNActionPerformed

    private void startBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBTNActionPerformed
        //start button in connect

        int remotePort = Integer.parseInt(portTB.getText());
        if (remotePort < 1 || remotePort > 0xFFFF) {
            throw new NumberFormatException("port must be in range [1, 65535]");
        }
        if ("127.0.0.1".equals(ipTB.getText()) || "localhost".equals(ipTB.getText())) {
            if (iedPath == null) {
                connectedLBL.setText("select a file");
                connectedLBL.setForeground(Color.black);

                LOGGER_GUI.error("no file selected\n");
            }
        }
        try {
            if (createServer.isSelected()) {
                server = new Server(iedPath, remotePort, IedLBL.getText());
                mainFrame.setEnabledAt(2, true);
                mainFrame.setEnabledAt(1, true);
                connectedLBL.setText("server started");
                connectedLBL.setForeground(Color.BLUE);
                LOGGER_GUI.info("server started\n");
            }
            try {
                client = new Client(ipTB.getText(), Integer.parseInt(portTB.getText()), server.serverModel);
                startBTN.setEnabled(false);
                stopBTN.setEnabled(true);
                selectFileBTN.setEnabled(false);
                changeIedBTN.setEnabled(false);
            } catch (NullPointerException e) {
                try {
                    client = new Client(ipTB.getText(), Integer.parseInt(portTB.getText()), null);
                    connectedLBL.setText("client connected");
                    connectedLBL.setForeground(Color.black);
                    LOGGER_GUI.error("only client connected");
                    startBTN.setEnabled(false);
                    stopBTN.setEnabled(true);
                    selectFileBTN.setEnabled(false);
                    changeIedBTN.setEnabled(false);
                    mainFrame.setEnabledAt(1, true);
                } catch (ConnectException ex) {
                    connectedLBL.setText("no server avaible");
                    connectedLBL.setForeground(Color.red);
                    LOGGER_GUI.error("no server found");
                } catch (IOException ex) {
                    LOGGER_GUI.error("error", ex);
                } catch (SclParseException ex) {
                    connectedLBL.setText("invalid scl file");
                    connectedLBL.setForeground(Color.red);
                    LOGGER_GUI.error("no server found");
                }
            } catch (IOException e) {
                LOGGER_GUI.error("error", e);
            }
        } catch (java.net.BindException | java.lang.NoSuchMethodError e) {
            connectedLBL.setText("port already in use");
            connectedLBL.setForeground(Color.red);
            LOGGER_GUI.error("port already in use");
        } catch (UnknownHostException e) {
            connectedLBL.setText("invalid ip");
            connectedLBL.setForeground(Color.red);
            LOGGER_GUI.error("invalid ip entered");
        } catch (NumberFormatException e) {
            LOGGER_GUI.error("port is not a valid number", e);
        } catch (SclParseException e) {
            LOGGER_GUI.error("scl parse exception", e);
        } catch (NullPointerException e) {
            connectedLBL.setText("no ied selected");
            connectedLBL.setForeground(Color.red);
            LOGGER_GUI.error("no ied selected", e);
        } catch (IOException e) {
            LOGGER_GUI.error("error", e);
        }

    }//GEN-LAST:event_startBTNActionPerformed

    private void setAllRbsFalse() {
        reserveReportRB.setSelected(false);
        cancelReservationRB.setSelected(false);
        disableReportRB.setSelected(false);
        enableReportRB.setSelected(false);
        setTriggerReportRB.setSelected(false);
        setDatasetReportRB.setSelected(false);
        setIntegrityReportRB.setSelected(false);
        sendGeneralInterrogationReportRB.setSelected(false);
    }

    private void setAllReportPnlsFalse() {
        IntegrityReportPNL.setVisible(false);
        valueReportPNL.setVisible(false);
        triggerOptionsReportPNL.setVisible(false);
        reserveTimeReportPNL.setVisible(false);
        referenceReportPNL.setVisible(false);
    }

//    private void setAllDatasetPnlsFalse() {
//        referenceDatasetPNL.setVisible(false);
//        fcDatasetPNL.setVisible(false);
//        numberOfEntriesDatasetPNL.setVisible(false);
//    }
    private void disableReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableReportRBActionPerformed
        setAllReportPnlsFalse();
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_disableReportRBActionPerformed

    private void enableReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableReportRBActionPerformed
        setAllReportPnlsFalse();
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_enableReportRBActionPerformed

    private void reserveReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveReportRBActionPerformed
        setAllReportPnlsFalse();
        reserveTimeReportPNL.setVisible(true);
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_reserveReportRBActionPerformed

    private void cancelReservationRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationRBActionPerformed
        setAllReportPnlsFalse();
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_cancelReservationRBActionPerformed

    private void setTriggerReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTriggerReportRBActionPerformed
        setAllReportPnlsFalse();
        triggerOptionsReportPNL.setVisible(true);
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_setTriggerReportRBActionPerformed

    private void setDatasetReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDatasetReportRBActionPerformed
        setAllReportPnlsFalse();
        triggerOptionsReportPNL.setVisible(true);
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_setDatasetReportRBActionPerformed

    private void setIntegrityReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setIntegrityReportRBActionPerformed
        setAllReportPnlsFalse();
        IntegrityReportPNL.setVisible(true);
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_setIntegrityReportRBActionPerformed

    private void sendGeneralInterrogationReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendGeneralInterrogationReportRBActionPerformed
        setAllReportPnlsFalse();
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_sendGeneralInterrogationReportRBActionPerformed

    private void reportStartBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportStartBTNActionPerformed
        String value = valueTB.getText();
        String triggerOptionsString = triggerOptionsTB.getText();
        String integrityPeriod = integrityPeriodTB.getText();
        String reference = referenceTB.getText();

        short time;
        try {
            time = Short.parseShort(reserveTimeTB.getText());
        } catch (NumberFormatException e) {
            //not a number
            time = 0;
            LOGGER_GUI.error("invalid number entered in report", e);
        }

        try {
            if (reserveReportRB.isSelected()) {
                client.reserveReport(reference, time);
            } else if (cancelReservationRB.isSelected()) {
                client.cancelReservation(reference);
            } else if (disableReportRB.isSelected()) {
                client.disableReport(reference);
            } else if (enableReportRB.isSelected()) {
                client.enableReport(reference);
            } else if (setTriggerReportRB.isSelected()) {
                client.setTriggerReport(reference, value);
            } else if (setDatasetReportRB.isSelected()) {
                client.setDatasetReport(reference, triggerOptionsString);
            } else if (setIntegrityReportRB.isSelected()) {
                client.setIntegrityReport(reference, integrityPeriod);
            } else if (sendGeneralInterrogationReportRB.isSelected()) {
                client.sendGeneralInterrogationReport(reference);
            } else {
                LOGGER_GUI.warn("no function selected\n");
            }
        } catch (ServiceError | IOException e) {
            LOGGER_GUI.error("error on report control", e);
        }
    }//GEN-LAST:event_reportStartBTNActionPerformed

    private void simulateRampStartBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateRampStartBTNActionPerformed

        String referenceRamp = simulateRampReferenceTB.getText();
        String fcString = simulateRampFcCB.getSelectedItem().toString();

        int from;
        int to;
        long time;
        int steps;
        LOGGER_GUI.info("ramp simulator started: ");
        try {
            time = Long.parseLong(simulateRampTimeTB.getText());
            steps = Integer.parseInt(simulateRampStepsTB.getText());
            from = Integer.parseInt(simulateRampFromTB.getText());
            to = Integer.parseInt(simulateRampToTB.getText());
        } catch (NumberFormatException e) {
            time = 0;
            from = 0;
            to = 0;
            steps = 0;
            LOGGER_GUI.error("invalid number entered in ramp simulator", e);
            simulateRampStopBTNActionPerformed(null);
        }
        enabled = true;
        simulateRampStartBTN.setEnabled(false);
        simulateRampStopBTN.setEnabled(true);
        try {
            Simulator sim = new Simulator(server);
            sim.rampSimulator(referenceRamp, fcString, from, to, time, steps);
        } catch (InterruptedException e) {
            LOGGER_GUI.error("error", e);
            // simulateRampStopBTNActionPerformed(null);
        }

    }//GEN-LAST:event_simulateRampStartBTNActionPerformed

    private void simulatePulsStartBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulatePulsStartBTNActionPerformed

        String referencePuls = simulatePulsReferenceTB.getText();
        String fcString = simulatePulsFcCB.getSelectedItem().toString();

        String min = simulatePulsMinTB.getText();
        String max = simulatePulsMaxTB.getText();
        long offTime;
        long onTime;
        try {
            offTime = Long.parseLong(simulatePulsTimeOffTB.getText());
            onTime = Long.parseLong(simulatePulsTimeOnTB.getText());
        } catch (NumberFormatException e) {
            LOGGER_GUI.error("invLID number entered in pulse simulator", e);
            offTime = 0;
            onTime = 0;
            simulatePulsStopBTNActionPerformed(null);
        }
        enabled = true;
        simulatePulsStartBTN.setEnabled(false);
        simulatePulsStopBTN.setEnabled(true);

        LOGGER_GUI.info("started pulse simulator\n");
        Simulator sim = new Simulator(server);
        try {
            sim.pulseSimulator(referencePuls, fcString, min, max, onTime, offTime);
        } catch (InterruptedException e) {
            LOGGER_GUI.error("error", e);
            //simulatePulsStopBTNActionPerformed(null);
        }

    }//GEN-LAST:event_simulatePulsStartBTNActionPerformed

    private void simulatePulsStopBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulatePulsStopBTNActionPerformed
        simulatePulsStartBTN.setEnabled(true);
        simulatePulsStopBTN.setEnabled(false);
        enabled = false;

        LOGGER_GUI.info("stopped pulse simulator\n");
    }//GEN-LAST:event_simulatePulsStopBTNActionPerformed

    private void selectReferenceReportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectReferenceReportBTNActionPerformed
        try {
            RefSelect select = new RefSelect(server.serverModel, true);
        } catch (UnknownHostException e) {
            LOGGER_GUI.error("error", e);
        }
    }//GEN-LAST:event_selectReferenceReportBTNActionPerformed

    private void selectReferenceRampBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectReferenceRampBTNActionPerformed
        try {
            RefSelect select = new RefSelect(server.serverModel, false);
        } catch (UnknownHostException e) {
            LOGGER_GUI.error("error", e);
        }
    }//GEN-LAST:event_selectReferenceRampBTNActionPerformed

    private void selectReferencePulsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectReferencePulsBTNActionPerformed
        try {
            RefSelect select = new RefSelect(server.serverModel, false);
        } catch (UnknownHostException e) {
            LOGGER_GUI.error("error", e);
        }
    }//GEN-LAST:event_selectReferencePulsBTNActionPerformed

    private void saveCsvBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCsvBTNActionPerformed
//simulate nehmen und in csv speichern 

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Specify a file to save");

        int rueckgabeWert = chooser.showSaveDialog(this);

        if (rueckgabeWert == JFileChooser.APPROVE_OPTION) {
            File fileToSave = chooser.getSelectedFile();
            try {
                String s = simLogTP.getText();
                File f = new File(fileToSave.getAbsolutePath() + ".txt");
                try ( FileWriter fw = new FileWriter(f)) {
                    fw.write(s);
                }
            } catch (IOException e) {
                LOGGER_GUI.error("Exception Caught : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_saveCsvBTNActionPerformed

    private void simulateRampStopBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateRampStopBTNActionPerformed
        simulateRampStartBTN.setEnabled(true);
        simulateRampStopBTN.setEnabled(false);
        enabled = false;

        LOGGER_GUI.info("stopped ramp simulator\n");
    }//GEN-LAST:event_simulateRampStopBTNActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        try {
            if (help == null) {
                help = new HelpWindow();
                help.setVisible(true);
            } else if (!help.isActive()) {
                help = new HelpWindow();
                help.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("error opening help window");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            Desktop.getDesktop().browse(new URL("https://github.com/mandybandy/openiec61850Simulator").toURI());
        } catch (MalformedURLException e) {
            LOGGER_GUI.error("error", e);
        } catch (URISyntaxException e) {
            LOGGER_GUI.error("error", e);
        } catch (IOException e) {
            LOGGER_GUI.error("error", e);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void createNetDeviceList() {

        try {
            netDevicesTA.setText(null);
            NetworkUtil.getNetDevice();
        } catch (SocketException e) {
            LOGGER_GUI.error("socket error", e);
        }

    }

    private void createNetInfoList(String iedName) {
        try {
            xml.setIed(iedName);
            netInfosTA.setEditable(false);
            for (int i = 0; i < xml.getIp().size(); i++) {
                netInfosTA.append(xml.getIp().get(i) + "\n");
            }
            netInfosTA.setCaretPosition(0);
        } catch (SAXException e) {
            LOGGER_GUI.error("error", e);
        } catch (IOException e) {
            LOGGER_GUI.error("error", e);
        } catch (ParserConfigurationException e) {
            LOGGER_GUI.error("error", e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Gui().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel IedLBL;
    public static javax.swing.JLabel IntegrityLBL;
    public static javax.swing.JPanel IntegrityReportPNL;
    public static javax.swing.JRadioButton cancelReservationRB;
    public static javax.swing.JButton changeIedBTN;
    public javax.swing.JPanel changeIedTAB;
    public static javax.swing.JButton changeValuesBTN;
    public static javax.swing.JPanel connectTAB;
    public static javax.swing.JLabel connectedLBL;
    public static javax.swing.JCheckBox createServer;
    public static javax.swing.ButtonGroup datasetBG;
    public static javax.swing.JRadioButton disableReportRB;
    public static javax.swing.JRadioButton enableReportRB;
    public static javax.swing.JLabel icodersclLBL;
    public static javax.swing.JTextField iedPathTB;
    public static javax.swing.JTextField integrityPeriodTB;
    public static javax.swing.JTextField ipTB;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel25;
    public static javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JMenu jMenu1;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JPanel jPanel12;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel7;
    public static javax.swing.JPanel jPanel8;
    public static javax.swing.JPanel jPanel9;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JScrollPane jScrollPane6;
    public static javax.swing.JSplitPane jSplitPane1;
    public static javax.swing.JSplitPane jSplitPane2;
    public static javax.swing.JSplitPane jSplitPane3;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTabbedPane jTabbedPane4;
    public static javax.swing.JPanel logTAB;
    public static javax.swing.JTabbedPane mainFrame;
    public static javax.swing.JTextPane masterLogTP;
    public static javax.swing.JTextArea netDevicesTA;
    public static javax.swing.JTextArea netInfosTA;
    public static javax.swing.JTextField portTB;
    public static javax.swing.JPanel radioButtonsReportPNL;
    public static javax.swing.JLabel referenceLBL;
    public static javax.swing.JPanel referenceReportPNL;
    public static javax.swing.JTextField referenceTB;
    public static javax.swing.ButtonGroup reportBG;
    public static javax.swing.JTextPane reportDatasetTP;
    public static javax.swing.JPanel reportPNL;
    public static javax.swing.JButton reportStartBTN;
    public static javax.swing.JRadioButton reserveReportRB;
    public static javax.swing.JLabel reserveTimeLBL;
    public static javax.swing.JPanel reserveTimeReportPNL;
    public static javax.swing.JTextField reserveTimeTB;
    public static javax.swing.JToggleButton saveCsvBTN;
    public static javax.swing.JButton selectFileBTN;
    public static javax.swing.JButton selectReferencePulsBTN;
    public static javax.swing.JButton selectReferenceRampBTN;
    public static javax.swing.JButton selectReferenceReportBTN;
    public static javax.swing.JLabel selectedIedLBL;
    public static javax.swing.JRadioButton sendGeneralInterrogationReportRB;
    public static javax.swing.JRadioButton setDatasetReportRB;
    public static javax.swing.JRadioButton setIntegrityReportRB;
    public static javax.swing.JRadioButton setTriggerReportRB;
    public static javax.swing.JTextPane simLogTP;
    public static javax.swing.JComboBox<String> simulatePulsFcCB;
    public static javax.swing.JTextField simulatePulsMaxTB;
    public static javax.swing.JTextField simulatePulsMinTB;
    public static javax.swing.JTextField simulatePulsReferenceTB;
    public static javax.swing.JToggleButton simulatePulsStartBTN;
    public static javax.swing.JButton simulatePulsStopBTN;
    public static javax.swing.JTextField simulatePulsTimeOffTB;
    public static javax.swing.JTextField simulatePulsTimeOnTB;
    public static javax.swing.JComboBox<String> simulateRampFcCB;
    public static javax.swing.JTextField simulateRampFromTB;
    public static javax.swing.JTextField simulateRampReferenceTB;
    public static javax.swing.JButton simulateRampStartBTN;
    public static javax.swing.JTextField simulateRampStepsTB;
    public static javax.swing.JButton simulateRampStopBTN;
    public static javax.swing.JTextField simulateRampTimeTB;
    public static javax.swing.JTextField simulateRampToTB;
    public javax.swing.JPanel simulateTAB;
    public static javax.swing.JButton startBTN;
    public static javax.swing.JButton stopBTN;
    public static javax.swing.JLabel triggerOptionsLBL;
    public static javax.swing.JPanel triggerOptionsReportPNL;
    public static javax.swing.JTextField triggerOptionsTB;
    public static javax.swing.JLabel valueLBL;
    public static javax.swing.JPanel valueReportPNL;
    public static javax.swing.JTextField valueTB;
    // End of variables declaration//GEN-END:variables
}
