package serverguiiec61850.gui;

import com.beanit.openiec61850.SclParseException;
import com.beanit.openiec61850.ServiceError;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;
import serverguiiec61850.network.Client;
import serverguiiec61850.network.Server;
import static serverguiiec61850.files.ModifyXmlFile.getIp;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import static serverguiiec61850.files.ModifyXmlFile.splitIed;
import serverguiiec61850.network.NetworkUtil;

/**
 *
 * @author Philipp Mandl
 */
public class Gui extends javax.swing.JFrame {

    public static final Logger LOGGER_GUI = LoggerFactory.getLogger(Gui.class);

    /**
     * path where the modified xml is
     */
    public static String iedPath = System.getProperty("user.dir") + "\\src\\main\\java\\serverguiiec61850\\files\\icd\\everyIed.xml";

    private Server server;
    private Client client;
    ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();

    public static boolean enabled = true;

    /**
     * Creates new form gui
     */
    public Gui() {
        super("IEC61850 Simulator");
        try {
            // Set System L&F
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        ImageIcon img = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\serverguiiec61850\\files\\icon.png");
        this.setIconImage(img.getImage());
        KeyListenerGui keyListenerGui = new KeyListenerGui();
        createNetDeviceList();
        JTextAreaAppender masterappender = new JTextAreaAppender(masterLogTA, simLogTA, reportDatasetTA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor(upps).
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datasetBG = new javax.swing.ButtonGroup();
        reportBG = new javax.swing.ButtonGroup();
        mainFrame = new javax.swing.JTabbedPane();
        connectTAB = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        iedPathTB = new javax.swing.JTextField();
        icodersclLBL = new javax.swing.JLabel();
        IedLBL = new javax.swing.JLabel();
        changeIedBTN = new javax.swing.JButton();
        selectedIedLBL = new javax.swing.JLabel();
        selectFileBTN = new javax.swing.JButton();
        networkPNL = new javax.swing.JPanel();
        startBTN = new javax.swing.JButton();
        portTB = new javax.swing.JTextField();
        ipTB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        connectedLBL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stopBTN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        netInfosTA = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        netDevicesTA = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        changeIedTAB = new javax.swing.JPanel();
        changeValuesBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        reportPNL = new javax.swing.JPanel();
        selectReferenceReportBTN = new javax.swing.JButton();
        reportStartBTN = new javax.swing.JButton();
        valueReportPNL = new javax.swing.JPanel();
        valueLBL = new javax.swing.JLabel();
        valueTB = new javax.swing.JTextField();
        referenceReportPNL = new javax.swing.JPanel();
        referenceLBL = new javax.swing.JLabel();
        referenceTB = new javax.swing.JTextField();
        reserveTimeReportPNL = new javax.swing.JPanel();
        reserveTimeLBL = new javax.swing.JLabel();
        reserveTimeTB = new javax.swing.JTextField();
        triggerOptionsReportPNL = new javax.swing.JPanel();
        triggerOptionsLBL = new javax.swing.JLabel();
        triggerOptionsTB = new javax.swing.JTextField();
        IntegrityReportPNL = new javax.swing.JPanel();
        IntegrityLBL = new javax.swing.JLabel();
        integrityPeriodTB = new javax.swing.JTextField();
        radioButtonsReportPNL = new javax.swing.JPanel();
        cancelReservationRB = new javax.swing.JRadioButton();
        setIntegrityReportRB = new javax.swing.JRadioButton();
        setTriggerReportRB = new javax.swing.JRadioButton();
        sendGeneralInterrogationReportRB = new javax.swing.JRadioButton();
        setDatasetReportRB = new javax.swing.JRadioButton();
        disableReportRB = new javax.swing.JRadioButton();
        enableReportRB = new javax.swing.JRadioButton();
        reserveReportRB = new javax.swing.JRadioButton();
        datasetPNL = new javax.swing.JPanel();
        createDatasetRB = new javax.swing.JRadioButton();
        deleteDatasetRB = new javax.swing.JRadioButton();
        startDatasetBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        referenceDatasetPNL = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        createDatasetRefTB = new javax.swing.JTextField();
        fcDatasetPNL = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        createDatasetFcCB = new javax.swing.JComboBox<>();
        numberOfEntriesDatasetPNL = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        createDatasetNumberOfEntriesTB = new javax.swing.JTextField();
        selectReferenceDatasetBTN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reportDatasetTA = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        simulateTAB = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        simLogTA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        saveCsvBTN = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        simulateRampFromTB = new javax.swing.JTextField();
        simulateRampStartBTN = new javax.swing.JButton();
        simulateRampToTB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        simulateRampTimeTB = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        simulateRampReferenceTB = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        simulateRampFcCB = new javax.swing.JComboBox<>();
        simulateRampStepsTB = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        selectReferenceRampBTN = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        simulatePulsMinTB = new javax.swing.JTextField();
        simulatePulsMaxTB = new javax.swing.JTextField();
        simulatePulsTimeOffTB = new javax.swing.JTextField();
        simulatePulsTimeOnTB = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        simulatePulsStartBTN = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        simulatePulsReferenceTB = new javax.swing.JTextField();
        simulatePulsFcCB = new javax.swing.JComboBox<>();
        simulatePulsStopBTN = new javax.swing.JButton();
        selectReferencePulsBTN = new javax.swing.JButton();
        logTAB = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        masterLogTA = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iedPathTB.setText("F:\\diplomarbeit\\project\\openiec61850Simulator\\serverguiiec61850\\src\\main\\java\\serverguiiec61850\\files");

        icodersclLBL.setText("ICD oder SCL file");

        IedLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IedLBL.setText("select IED");

        changeIedBTN.setText("change");
        changeIedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeIedBTNActionPerformed(evt);
            }
        });

        selectedIedLBL.setText("selected IED: ");

        selectFileBTN.setText("select file");
        selectFileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileBTNActionPerformed(evt);
            }
        });

        startBTN.setText("start Server");
        startBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBTNActionPerformed(evt);
            }
        });

        portTB.setText("102");

        ipTB.setText("127.0.0.1");

        jLabel1.setText("ip");

        jLabel5.setText("port");

        connectedLBL.setText("not connected");

        jLabel6.setText(":");

        stopBTN.setText("stop Server");
        stopBTN.setEnabled(false);
        stopBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBTNActionPerformed(evt);
            }
        });

        jLabel10.setText("connect to:");

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        netInfosTA.setColumns(20);
        netInfosTA.setRows(5);
        netInfosTA.setText("IP: 0.0.0.0\nIP-SUBNET: 0.0.0.0\nIP-GATEWAY: 0.0.0.0");
        jScrollPane2.setViewportView(netInfosTA);

        netDevicesTA.setColumns(20);
        netDevicesTA.setRows(5);
        netDevicesTA.setText("found no devices");
        jScrollPane5.setViewportView(netDevicesTA);

        jLabel9.setText("Network Devices:");

        jLabel15.setText("address settings in file:");

        javax.swing.GroupLayout networkPNLLayout = new javax.swing.GroupLayout(networkPNL);
        networkPNL.setLayout(networkPNLLayout);
        networkPNLLayout.setHorizontalGroup(
            networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPNLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(networkPNLLayout.createSequentialGroup()
                        .addGroup(networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(networkPNLLayout.createSequentialGroup()
                                .addComponent(ipTB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(portTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(networkPNLLayout.createSequentialGroup()
                        .addComponent(startBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stopBTN))
                    .addComponent(connectedLBL))
                .addContainerGap(327, Short.MAX_VALUE))
            .addGroup(networkPNLLayout.createSequentialGroup()
                .addGroup(networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        networkPNLLayout.setVerticalGroup(
            networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPNLLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(networkPNLLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(networkPNLLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(networkPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBTN)
                    .addComponent(stopBTN))
                .addGap(18, 18, 18)
                .addComponent(connectedLBL)
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icodersclLBL)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(selectedIedLBL)
                        .addGap(44, 44, 44)
                        .addComponent(IedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeIedBTN))
                    .addComponent(iedPathTB, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectFileBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(networkPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(icodersclLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iedPathTB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeIedBTN)
                    .addComponent(selectedIedLBL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(networkPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout connectTABLayout = new javax.swing.GroupLayout(connectTAB);
        connectTAB.setLayout(connectTABLayout);
        connectTABLayout.setHorizontalGroup(
            connectTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectTABLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        connectTABLayout.setVerticalGroup(
            connectTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectTABLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        mainFrame.addTab("connect", connectTAB);

        changeIedTAB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changeValuesBTN.setText("change server manual");
        changeValuesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeValuesBTNActionPerformed(evt);
            }
        });
        changeIedTAB.add(changeValuesBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, 70));
        changeIedTAB.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 13, -1, -1));

        selectReferenceReportBTN.setText("select Reference");
        selectReferenceReportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectReferenceReportBTNActionPerformed(evt);
            }
        });

        reportStartBTN.setText("do");
        reportStartBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportStartBTNActionPerformed(evt);
            }
        });

        valueReportPNL.setPreferredSize(new java.awt.Dimension(120, 30));

        valueLBL.setText("value:");

        valueTB.setText("value");

        javax.swing.GroupLayout valueReportPNLLayout = new javax.swing.GroupLayout(valueReportPNL);
        valueReportPNL.setLayout(valueReportPNLLayout);
        valueReportPNLLayout.setHorizontalGroup(
            valueReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valueReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valueLBL)
                .addGap(42, 42, 42)
                .addComponent(valueTB, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        valueReportPNLLayout.setVerticalGroup(
            valueReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valueReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valueReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLBL)
                    .addComponent(valueTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        referenceReportPNL.setPreferredSize(new java.awt.Dimension(139, 30));

        referenceLBL.setText("reference:");

        referenceTB.setText("IED1/LogicalNode.underLN.value");

        javax.swing.GroupLayout referenceReportPNLLayout = new javax.swing.GroupLayout(referenceReportPNL);
        referenceReportPNL.setLayout(referenceReportPNLLayout);
        referenceReportPNLLayout.setHorizontalGroup(
            referenceReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referenceReportPNLLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(referenceLBL)
                .addGap(36, 36, 36)
                .addComponent(referenceTB, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        referenceReportPNLLayout.setVerticalGroup(
            referenceReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referenceReportPNLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(referenceReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceLBL)
                    .addComponent(referenceTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        reserveTimeReportPNL.setPreferredSize(new java.awt.Dimension(135, 30));
        reserveTimeReportPNL.setVerifyInputWhenFocusTarget(false);

        reserveTimeLBL.setText("reserve time:");

        reserveTimeTB.setText("5");

        javax.swing.GroupLayout reserveTimeReportPNLLayout = new javax.swing.GroupLayout(reserveTimeReportPNL);
        reserveTimeReportPNL.setLayout(reserveTimeReportPNLLayout);
        reserveTimeReportPNLLayout.setHorizontalGroup(
            reserveTimeReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTimeReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reserveTimeLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(reserveTimeTB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        reserveTimeReportPNLLayout.setVerticalGroup(
            reserveTimeReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTimeReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reserveTimeReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveTimeLBL)
                    .addComponent(reserveTimeTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        triggerOptionsLBL.setText("trigger options:");

        triggerOptionsTB.setText("trigger");

        javax.swing.GroupLayout triggerOptionsReportPNLLayout = new javax.swing.GroupLayout(triggerOptionsReportPNL);
        triggerOptionsReportPNL.setLayout(triggerOptionsReportPNLLayout);
        triggerOptionsReportPNLLayout.setHorizontalGroup(
            triggerOptionsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(triggerOptionsReportPNLLayout.createSequentialGroup()
                .addComponent(triggerOptionsLBL)
                .addGap(39, 39, 39)
                .addComponent(triggerOptionsTB, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        triggerOptionsReportPNLLayout.setVerticalGroup(
            triggerOptionsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(triggerOptionsReportPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(triggerOptionsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(triggerOptionsLBL)
                    .addComponent(triggerOptionsTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        IntegrityReportPNL.setPreferredSize(new java.awt.Dimension(172, 30));

        IntegrityLBL.setText("integrityPeriod:");

        javax.swing.GroupLayout IntegrityReportPNLLayout = new javax.swing.GroupLayout(IntegrityReportPNL);
        IntegrityReportPNL.setLayout(IntegrityReportPNLLayout);
        IntegrityReportPNLLayout.setHorizontalGroup(
            IntegrityReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntegrityReportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IntegrityLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(integrityPeriodTB, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        IntegrityReportPNLLayout.setVerticalGroup(
            IntegrityReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntegrityReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(integrityPeriodTB)
                .addComponent(IntegrityLBL))
        );

        reportBG.add(cancelReservationRB);
        cancelReservationRB.setText("cancel reservation");
        cancelReservationRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationRBActionPerformed(evt);
            }
        });

        reportBG.add(setIntegrityReportRB);
        setIntegrityReportRB.setText("set integrity");
        setIntegrityReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setIntegrityReportRBActionPerformed(evt);
            }
        });

        reportBG.add(setTriggerReportRB);
        setTriggerReportRB.setText("set trigger");
        setTriggerReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTriggerReportRBActionPerformed(evt);
            }
        });

        reportBG.add(sendGeneralInterrogationReportRB);
        sendGeneralInterrogationReportRB.setText("send generell interrogation");
        sendGeneralInterrogationReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendGeneralInterrogationReportRBActionPerformed(evt);
            }
        });

        reportBG.add(setDatasetReportRB);
        setDatasetReportRB.setText("set dataset");
        setDatasetReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDatasetReportRBActionPerformed(evt);
            }
        });

        reportBG.add(disableReportRB);
        disableReportRB.setText("disable report");
        disableReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableReportRBActionPerformed(evt);
            }
        });

        reportBG.add(enableReportRB);
        enableReportRB.setText("enable report");
        enableReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableReportRBActionPerformed(evt);
            }
        });

        reportBG.add(reserveReportRB);
        reserveReportRB.setText("reserve Report (in log)");
        reserveReportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveReportRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioButtonsReportPNLLayout = new javax.swing.GroupLayout(radioButtonsReportPNL);
        radioButtonsReportPNL.setLayout(radioButtonsReportPNLLayout);
        radioButtonsReportPNLLayout.setHorizontalGroup(
            radioButtonsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonsReportPNLLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(radioButtonsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveReportRB)
                    .addComponent(cancelReservationRB)
                    .addComponent(setIntegrityReportRB)
                    .addComponent(setDatasetReportRB)
                    .addComponent(sendGeneralInterrogationReportRB)
                    .addGroup(radioButtonsReportPNLLayout.createSequentialGroup()
                        .addComponent(disableReportRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enableReportRB))
                    .addComponent(setTriggerReportRB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        radioButtonsReportPNLLayout.setVerticalGroup(
            radioButtonsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonsReportPNLLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(reserveReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelReservationRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setIntegrityReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setTriggerReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendGeneralInterrogationReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setDatasetReportRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(radioButtonsReportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disableReportRB)
                    .addComponent(enableReportRB))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout reportPNLLayout = new javax.swing.GroupLayout(reportPNL);
        reportPNL.setLayout(reportPNLLayout);
        reportPNLLayout.setHorizontalGroup(
            reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonsReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPNLLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(IntegrityReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reportPNLLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(referenceReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectReferenceReportBTN))
                    .addGroup(reportPNLLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(triggerOptionsReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(reportStartBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reserveTimeReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportPNLLayout.setVerticalGroup(
            reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPNLLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPNLLayout.createSequentialGroup()
                        .addComponent(radioButtonsReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 337, Short.MAX_VALUE))
                    .addGroup(reportPNLLayout.createSequentialGroup()
                        .addGroup(reportPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referenceReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectReferenceReportBTN))
                        .addGap(18, 18, 18)
                        .addComponent(IntegrityReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triggerOptionsReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reserveTimeReportPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reportStartBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane4.addTab("report", reportPNL);

        datasetBG.add(createDatasetRB);
        createDatasetRB.setText("create dataset");
        createDatasetRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDatasetRBActionPerformed(evt);
            }
        });

        datasetBG.add(deleteDatasetRB);
        deleteDatasetRB.setText("delete dataset");
        deleteDatasetRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDatasetRBActionPerformed(evt);
            }
        });

        startDatasetBTN.setText("do");
        startDatasetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDatasetBTNActionPerformed(evt);
            }
        });

        jLabel11.setText("reference");

        createDatasetRefTB.setText("IED1/LogicalNode.underLN.value");

        javax.swing.GroupLayout referenceDatasetPNLLayout = new javax.swing.GroupLayout(referenceDatasetPNL);
        referenceDatasetPNL.setLayout(referenceDatasetPNLLayout);
        referenceDatasetPNLLayout.setHorizontalGroup(
            referenceDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referenceDatasetPNLLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createDatasetRefTB, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        referenceDatasetPNLLayout.setVerticalGroup(
            referenceDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referenceDatasetPNLLayout.createSequentialGroup()
                .addGroup(referenceDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(createDatasetRefTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel12.setText("fc");

        createDatasetFcCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ST","MX","SP","SV","CF","DC","SG","SE","SR","OR","BL","EX","CO","US","MS","RP","BR","LG", "GO", "GS","ALL","NONE" }));

        javax.swing.GroupLayout fcDatasetPNLLayout = new javax.swing.GroupLayout(fcDatasetPNL);
        fcDatasetPNL.setLayout(fcDatasetPNLLayout);
        fcDatasetPNLLayout.setHorizontalGroup(
            fcDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fcDatasetPNLLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addGap(35, 35, 35)
                .addComponent(createDatasetFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        fcDatasetPNLLayout.setVerticalGroup(
            fcDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fcDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(createDatasetFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel13.setText("number of entries");

        createDatasetNumberOfEntriesTB.setText("5");

        javax.swing.GroupLayout numberOfEntriesDatasetPNLLayout = new javax.swing.GroupLayout(numberOfEntriesDatasetPNL);
        numberOfEntriesDatasetPNL.setLayout(numberOfEntriesDatasetPNLLayout);
        numberOfEntriesDatasetPNLLayout.setHorizontalGroup(
            numberOfEntriesDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberOfEntriesDatasetPNLLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(createDatasetNumberOfEntriesTB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        numberOfEntriesDatasetPNLLayout.setVerticalGroup(
            numberOfEntriesDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberOfEntriesDatasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(createDatasetNumberOfEntriesTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        selectReferenceDatasetBTN.setText("select reference");
        selectReferenceDatasetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectReferenceDatasetBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fcDatasetPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectReferenceDatasetBTN)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(referenceDatasetPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(numberOfEntriesDatasetPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(referenceDatasetPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fcDatasetPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectReferenceDatasetBTN))
                .addGap(20, 20, 20)
                .addComponent(numberOfEntriesDatasetPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout datasetPNLLayout = new javax.swing.GroupLayout(datasetPNL);
        datasetPNL.setLayout(datasetPNLLayout);
        datasetPNLLayout.setHorizontalGroup(
            datasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datasetPNLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(startDatasetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(datasetPNLLayout.createSequentialGroup()
                .addGroup(datasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datasetPNLLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(createDatasetRB)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDatasetRB))
                    .addGroup(datasetPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        datasetPNLLayout.setVerticalGroup(
            datasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datasetPNLLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(datasetPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createDatasetRB)
                    .addComponent(deleteDatasetRB))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(startDatasetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane4.addTab("dataset", datasetPNL);

        changeIedTAB.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 830, 610));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        changeIedTAB.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 345, 232));

        reportDatasetTA.setEditable(false);
        reportDatasetTA.setColumns(20);
        reportDatasetTA.setEditable(false);
        reportDatasetTA.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        reportDatasetTA.setRows(5);
        jScrollPane4.setViewportView(reportDatasetTA);

        changeIedTAB.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 370, 480));

        jLabel14.setText("client:");
        changeIedTAB.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        mainFrame.addTab("change IED", changeIedTAB);

        jSplitPane1.setDividerLocation(300);

        simLogTA.setEditable(false);
        simLogTA.setColumns(20);
        simLogTA.setRows(5);
        jScrollPane1.setViewportView(simLogTA);

        jLabel3.setText("Values changed by simulator:");

        saveCsvBTN.setText("save .csv");
        saveCsvBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCsvBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(saveCsvBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 814, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(saveCsvBTN)
                .addGap(19, 19, 19))
        );

        jSplitPane1.setRightComponent(jPanel7);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        simulateRampFromTB.setText("0");

        simulateRampStartBTN.setText("start");
        simulateRampStartBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateRampStartBTNActionPerformed(evt);
            }
        });

        simulateRampToTB.setText("100");

        jLabel7.setText("from");

        jLabel8.setText("to");

        simulateRampTimeTB.setText("10000");

        jLabel20.setText("time ms");

        simulateRampReferenceTB.setText("IED1/LogicalNode.underLN.value");

        jLabel21.setText("Reference");

        jLabel22.setText("FC");

        simulateRampFcCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ST","MX","SP","SV","CF","DC","SG","SE","SR","OR","BL","EX","CO","US","MS","RP","BR","LG", "GO", "GS","ALL","NONE" }));

        simulateRampStepsTB.setText("100");

        jLabel25.setText("steps");

        selectReferenceRampBTN.setText("select reference");
        selectReferenceRampBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectReferenceRampBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simulateRampReferenceTB, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(simulateRampFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simulateRampStartBTN)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(simulateRampTimeTB)
                                    .addComponent(jLabel20)
                                    .addComponent(simulateRampFromTB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel25)
                                    .addComponent(simulateRampStepsTB)
                                    .addComponent(jLabel8)
                                    .addComponent(simulateRampToTB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(selectReferenceRampBTN))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(simulateRampReferenceTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(simulateRampFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(selectReferenceRampBTN)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulateRampFromTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulateRampToTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulateRampTimeTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulateRampStepsTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(simulateRampStartBTN)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ramp", jPanel2);

        simulatePulsMinTB.setText("0");

        simulatePulsMaxTB.setText("10");

        simulatePulsTimeOffTB.setText("1");

        simulatePulsTimeOnTB.setText("2000");

        jLabel16.setText("min");

        jLabel17.setText("max");

        jLabel18.setText("time off ms");

        jLabel19.setText("time on ms");

        simulatePulsStartBTN.setText("start");
        simulatePulsStartBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulatePulsStartBTNActionPerformed(evt);
            }
        });

        jLabel23.setText("Reference");

        jLabel24.setText("FC");

        simulatePulsReferenceTB.setText("IED1/LogicalNode.underLN.value");

        simulatePulsFcCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ST","MX","SP","SV","CF","DC","SG","SE","SR","OR","BL","EX","CO","US","MS","RP","BR","LG", "GO", "GS","ALL","NONE" }));

        simulatePulsStopBTN.setText("stop");
        simulatePulsStopBTN.setEnabled(false);
        simulatePulsStopBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulatePulsStopBTNActionPerformed(evt);
            }
        });

        selectReferencePulsBTN.setText("select reference");
        selectReferencePulsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectReferencePulsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(simulatePulsFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 134, Short.MAX_VALUE))
                            .addComponent(simulatePulsReferenceTB)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel23))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectReferencePulsBTN)
                                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(simulatePulsStartBTN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(simulatePulsTimeOffTB, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel18)
                                                .addComponent(simulatePulsMinTB, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(60, 60, 60)
                                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel17)
                                                .addComponent(simulatePulsTimeOnTB, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(simulatePulsMaxTB, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addComponent(simulatePulsStopBTN)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(simulatePulsReferenceTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(simulatePulsFcCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(selectReferencePulsBTN)
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulatePulsMinTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulatePulsMaxTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulatePulsTimeOffTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulatePulsTimeOnTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simulatePulsStartBTN)
                    .addComponent(simulatePulsStopBTN))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("puls", jPanel12);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(jPanel8);

        javax.swing.GroupLayout simulateTABLayout = new javax.swing.GroupLayout(simulateTAB);
        simulateTAB.setLayout(simulateTABLayout);
        simulateTABLayout.setHorizontalGroup(
            simulateTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        simulateTABLayout.setVerticalGroup(
            simulateTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulateTABLayout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainFrame.addTab("simulate", simulateTAB);

        masterLogTA.setEditable(false);
        masterLogTA.setColumns(20);
        masterLogTA.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        masterLogTA.setRows(5);
        jScrollPane3.setViewportView(masterLogTA);

        jLabel26.setText("log:");

        javax.swing.GroupLayout logTABLayout = new javax.swing.GroupLayout(logTAB);
        logTAB.setLayout(logTABLayout);
        logTABLayout.setHorizontalGroup(
            logTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTABLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(logTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        logTABLayout.setVerticalGroup(
            logTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTABLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        mainFrame.addTab("log", logTAB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainFrame)
                .addContainerGap())
        );

        mainFrame.setEnabledAt(1, false);
        mainFrame.setEnabledAt(2, false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeValuesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeValuesBTNActionPerformed
        try {
            GuiTree changevalues = new GuiTree();
            LOGGER_GUI.info("change values manual \n");
        } catch (UnknownHostException ex) {
            LOGGER_GUI.error("unknmown host", ex);
        }
    }//GEN-LAST:event_changeValuesBTNActionPerformed

    private void changeIedBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeIedBTNActionPerformed
        // JFileChooser-Objekt erstellen
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(System.getProperty("user.dir") + "\\src\\main\\java\\serverguiiec61850\\files\\icd\\"));
        // Dialog zum Oeffnen von Dateien anzeigen
        int rueckgabeWert = chooser.showDialog(this, "select IED");
        String iedPathName = "no IED selected";
        if (rueckgabeWert == JFileChooser.APPROVE_OPTION) {
            iedPath = chooser.getSelectedFile().getPath();
            iedPathName = chooser.getSelectedFile().getName();
        }

        netInfosTA.setText(null);
        try {
//            iedPathName = iedPathName.substring(0, iedPathName.lastIndexOf("."));
            createNetInfoList(iedPathName);
//        } catch (StringIndexOutOfBoundsException e) {
//            LOGGER_GUI.error("more than one . in filename is not permitted", e);
        } catch (NullPointerException e) {
            LOGGER_GUI.error("no addressblock found", e);
        }
        IedLBL.setText(iedPathName);
        LOGGER_GUI.info("changed IED " + iedPathName + "\n");
    }//GEN-LAST:event_changeIedBTNActionPerformed

    private void selectFileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileBTNActionPerformed

        // JFileChooser-Objekt erstellen
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(iedPathTB.getText()).getParentFile());
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("scd,scl,icd,xml files (*.scd,*.scl,*.icd,*.xml)", "scd", "scl", "icd", "xml");
        chooser.setFileFilter(filter);

        int rueckgabeWert = chooser.showDialog(this, "select a SCD/ICD file");

        if (rueckgabeWert == JFileChooser.APPROVE_OPTION) {
            System.out.println("The path of the file is: " + chooser.getSelectedFile().getPath());
            iedPathTB.setText(chooser.getSelectedFile().getPath());
            LOGGER_GUI.info("changed SCD/ICD file, new file: " + chooser.getSelectedFile().getName() + "\n");
        }

        File dir = new File(iedPath).getParentFile();
        if (dir.isDirectory()) {
            String[] entries = dir.list();
            for (String entrie : entries) {
                File aktFile = new File(dir.getPath(), entrie);
                aktFile.delete();
            }
        }

        try {
            splitIed(iedPathTB.getText());
        } catch (TransformerException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
            changeIedBTNActionPerformed(null);
        }
    }//GEN-LAST:event_selectFileBTNActionPerformed

    private void stopBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBTNActionPerformed
        //stop button in connect
        try {
            client.quit();
            server.quit();

            startBTN.setEnabled(true);
            stopBTN.setEnabled(false);
            mainFrame.setEnabledAt(1, false);
            mainFrame.setEnabledAt(2, false);
            connectedLBL.setText("server stopped");
            LOGGER_GUI.info("\n server stopped\n");
        } catch (Exception e) {
            connectedLBL.setText("error");
            LOGGER_GUI.error("error while closing server and client", e);
        }
    }//GEN-LAST:event_stopBTNActionPerformed

    private void startBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBTNActionPerformed
        //start button in connect
        try {
            int remotePort = Integer.parseInt(portTB.getText());
            if (remotePort < 1 || remotePort > 0xFFFF) {
                throw new NumberFormatException("port must be in range [1, 65535]");
            }
            if (iedPath == null) {
                connectedLBL.setText("select a file");
                LOGGER_GUI.error("no file selected\n");
            }
            server = new Server(iedPath, remotePort);
            client = new Client(ipTB.getText(), Integer.parseInt(portTB.getText()));

            //btn hide machen
            startBTN.setEnabled(false);
            stopBTN.setEnabled(true);

            mainFrame.setEnabledAt(1, true);
            mainFrame.setEnabledAt(2, true);

            connectedLBL.setText("server started");
            LOGGER_GUI.info("server started\n");
        } catch (NumberFormatException e) {
            //todo get error  
            LOGGER_GUI.error("", e);
        } catch (IOException ex) {
            LOGGER_GUI.error("", ex);
        } catch (SclParseException ex) {
            LOGGER_GUI.error("", ex);
        }
    }//GEN-LAST:event_startBTNActionPerformed

    private void setAllRbsFalse() {
        reserveReportRB.setSelected(false);
        cancelReservationRB.setSelected(false);
        disableReportRB.setSelected(false);
        enableReportRB.setSelected(false);
        setTriggerReportRB.setSelected(false);
        setDatasetReportRB.setSelected(false);
        setIntegrityReportRB.setSelected(false);
        sendGeneralInterrogationReportRB.setSelected(false);
    }

    private void setAllReportPnlsFalse() {
        IntegrityReportPNL.setVisible(false);
        valueReportPNL.setVisible(false);
        triggerOptionsReportPNL.setVisible(false);
        reserveTimeReportPNL.setVisible(false);
        referenceReportPNL.setVisible(false);
    }

    private void setAllDatasetPnlsFalse() {
        referenceDatasetPNL.setVisible(false);
        fcDatasetPNL.setVisible(false);
        numberOfEntriesDatasetPNL.setVisible(false);
    }

    private void disableReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableReportRBActionPerformed
        setAllReportPnlsFalse();
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_disableReportRBActionPerformed

    private void enableReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableReportRBActionPerformed
        setAllReportPnlsFalse();
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_enableReportRBActionPerformed

    private void reserveReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveReportRBActionPerformed
        setAllReportPnlsFalse();
        reserveTimeReportPNL.setVisible(true);
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_reserveReportRBActionPerformed

    private void cancelReservationRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationRBActionPerformed
        setAllReportPnlsFalse();
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_cancelReservationRBActionPerformed

    private void setTriggerReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTriggerReportRBActionPerformed
        setAllReportPnlsFalse();
        triggerOptionsReportPNL.setVisible(true);
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_setTriggerReportRBActionPerformed

    private void setDatasetReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDatasetReportRBActionPerformed
        setAllReportPnlsFalse();
        triggerOptionsReportPNL.setVisible(true);
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_setDatasetReportRBActionPerformed

    private void setIntegrityReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setIntegrityReportRBActionPerformed
        setAllReportPnlsFalse();
        IntegrityReportPNL.setVisible(true);
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_setIntegrityReportRBActionPerformed

    private void sendGeneralInterrogationReportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendGeneralInterrogationReportRBActionPerformed
        setAllReportPnlsFalse();
        referenceReportPNL.setVisible(true);
    }//GEN-LAST:event_sendGeneralInterrogationReportRBActionPerformed

    private void reportStartBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportStartBTNActionPerformed
        String value = valueTB.getText();
        String triggerOptionsString = triggerOptionsTB.getText();
        String integrityPeriod = integrityPeriodTB.getText();
        String reference = referenceTB.getText();

        short time;
        try {
            time = Short.parseShort(reserveTimeTB.getText());
        } catch (NumberFormatException e) {
            //not a number
            time = 0;
            LOGGER_GUI.error("a non number entered in report", e);
        }

        try {
            if (reserveReportRB.isSelected()) {
                LOGGER_GUI.info(client.reserveReport(reference, time));
            } else if (cancelReservationRB.isSelected()) {
                LOGGER_GUI.info(client.cancelReservation(reference));
            } else if (disableReportRB.isSelected()) {
                LOGGER_GUI.info(client.disableReport(reference));
            } else if (enableReportRB.isSelected()) {
                LOGGER_GUI.info(client.enableReport(reference));
            } else if (setTriggerReportRB.isSelected()) {
                LOGGER_GUI.info(client.setTriggerReport(reference, value));
            } else if (setDatasetReportRB.isSelected()) {
                LOGGER_GUI.info(client.setDatasetReport(reference, triggerOptionsString));
            } else if (setIntegrityReportRB.isSelected()) {
                LOGGER_GUI.info(client.setIntegrityReport(reference, integrityPeriod));
            } else if (sendGeneralInterrogationReportRB.isSelected()) {
                LOGGER_GUI.info(client.sendGeneralInterrogationReport(reference));
            } else {
                LOGGER_GUI.warn("no function selected\n");
            }
            reportDatasetTA.append("\n");
        } catch (ServiceError | IOException e) {
//ToDo Error
            LOGGER_GUI.error("", e);
        }
    }//GEN-LAST:event_reportStartBTNActionPerformed

    private void createDatasetRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDatasetRBActionPerformed
        referenceDatasetPNL.setVisible(true);
        fcDatasetPNL.setVisible(true);
        numberOfEntriesDatasetPNL.setVisible(true);
    }//GEN-LAST:event_createDatasetRBActionPerformed

    private void deleteDatasetRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDatasetRBActionPerformed
        setAllDatasetPnlsFalse();
        referenceDatasetPNL.setVisible(true);
    }//GEN-LAST:event_deleteDatasetRBActionPerformed

    private void startDatasetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDatasetBTNActionPerformed
        String numberOfEntriesString = createDatasetNumberOfEntriesTB.getText();
        String reference = createDatasetRefTB.getText();
        String fc = createDatasetFcCB.getSelectedItem().toString();
        try {
            if (createDatasetRB.isSelected()) {
                LOGGER_GUI.info(client.createdataset(reference, fc, numberOfEntriesString));
            } else if (deleteDatasetRB.isSelected()) {
                LOGGER_GUI.info(client.deletedataset(reference));
            } else {
                //nothing selected
                LOGGER_GUI.warn("no function selected\n");
            }
            reportDatasetTA.append("\n");
        } catch (ServiceError | IOException e) {
            LOGGER_GUI.error("service error ", e);
        }

    }//GEN-LAST:event_startDatasetBTNActionPerformed

    private void simulateRampStartBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateRampStartBTNActionPerformed
        String referenceRamp = simulateRampReferenceTB.getText();
        String fcString = simulateRampFcCB.getSelectedItem().toString();

        int from;
        int to;
        long time;
        int steps;
        LOGGER_GUI.info("ramp simulator started: ");
        try {
            time = Long.parseLong(simulateRampTimeTB.getText());
            steps = Integer.parseInt(simulateRampStepsTB.getText());
            from = Integer.parseInt(simulateRampFromTB.getText());
            to = Integer.parseInt(simulateRampToTB.getText());
        } catch (NumberFormatException e) {
            time = 0;
            from = 0;
            to = 0;
            steps = 0;
            LOGGER_GUI.error("a non number entered in ramp simulator", e);
        }

        try {
            Simulator sim = new Simulator(server);
            sim.rampSimulator(referenceRamp, fcString, from, to, time, steps);
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_simulateRampStartBTNActionPerformed

    private void simulatePulsStartBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulatePulsStartBTNActionPerformed
        String referencePuls = simulatePulsReferenceTB.getText();
        String fcString = simulatePulsFcCB.getSelectedItem().toString();

        String min = simulatePulsMinTB.getText();
        String max = simulatePulsMaxTB.getText();
        long offTime;
        long onTime;
        try {
            offTime = Long.parseLong(simulatePulsTimeOffTB.getText());
            onTime = Long.parseLong(simulatePulsTimeOnTB.getText());
        } catch (NumberFormatException e) {
            LOGGER_GUI.error("a non number entered in pulse simulator", e);
            offTime = 0;
            onTime = 0;
        }
        enabled = true;
        simulatePulsStartBTN.setEnabled(false);
        simulatePulsStopBTN.setEnabled(true);

        LOGGER_GUI.info("started pulse simulator\n");
        Simulator sim = new Simulator(server);
        try {
            sim.pulseSimulator(referencePuls, fcString, min, max, onTime, offTime);
//        try {
//            server.writeValue(referencePuls, fcString, max);
//            //ontime
//            Thread.sleep(onTime);
//            server.writeValue(referencePuls, fcString, min);
//            //offtime
//            Thread.sleep(offTime);
//        } catch (InterruptedException ex) {
//            LOGGER_GUI.error("simulator interrupted", ex);
//        }
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_simulatePulsStartBTNActionPerformed

    private void simulatePulsStopBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulatePulsStopBTNActionPerformed
        simulatePulsStartBTN.setEnabled(true);
        simulatePulsStopBTN.setEnabled(false);
        enabled = false;

        LOGGER_GUI.info("stopped pulse simulator\n");
    }//GEN-LAST:event_simulatePulsStopBTNActionPerformed

    private void selectReference(java.awt.event.ActionEvent evt) {
        try {
            RefSelect select = new RefSelect();
        } catch (UnknownHostException ex) {
            LOGGER_GUI.error("unknown host", ex);
        }
    }

    private void selectReferenceReportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectReferenceReportBTNActionPerformed
        selectReference(evt);
    }//GEN-LAST:event_selectReferenceReportBTNActionPerformed

    private void selectReferenceDatasetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectReferenceDatasetBTNActionPerformed
        selectReference(evt);
    }//GEN-LAST:event_selectReferenceDatasetBTNActionPerformed

    private void selectReferenceRampBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectReferenceRampBTNActionPerformed
        selectReference(evt);
    }//GEN-LAST:event_selectReferenceRampBTNActionPerformed

    private void selectReferencePulsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectReferencePulsBTNActionPerformed
        selectReference(evt);
    }//GEN-LAST:event_selectReferencePulsBTNActionPerformed

    private void saveCsvBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCsvBTNActionPerformed
//simulate nehmen und in csv speichern 

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Specify a file to save");

        int rueckgabeWert = chooser.showSaveDialog(this);

        if (rueckgabeWert == JFileChooser.APPROVE_OPTION) {
            File fileToSave = chooser.getSelectedFile();
            try {
                String s = simLogTA.getText();
                File f = new File(fileToSave.getAbsolutePath() + ".txt");
                try ( FileWriter fw = new FileWriter(f)) {
                    fw.write(s);
                }
            } catch (IOException ioe) {
                System.out.println("Exception Caught : " + ioe.getMessage());
            }
        }
    }//GEN-LAST:event_saveCsvBTNActionPerformed

    private void createNetDeviceList() {

        try {
            netDevicesTA.setText(null);
            netDevicesTA.setEditable(false);
            NetworkUtil.getNetDevice();
        } catch (SocketException ex) {
            LOGGER_GUI.error("socket error", ex);
        }

    }

    private void createNetInfoList(String iedName) {
        try {
            netInfosTA.setEditable(false);
            for (int i = 0; i < getIp(iedPath, iedName).size(); i++) {
                netInfosTA.append(getIp(iedPath, iedName).get(i) + "\n");
            }
        } catch (SAXException ex) {
            LOGGER_GUI.error("", ex);
        } catch (IOException ex) {
            LOGGER_GUI.error("", ex);
        } catch (ParserConfigurationException ex) {
            LOGGER_GUI.error("", ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Gui().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel IedLBL;
    public static javax.swing.JLabel IntegrityLBL;
    public static javax.swing.JPanel IntegrityReportPNL;
    public static javax.swing.JRadioButton cancelReservationRB;
    public static javax.swing.JButton changeIedBTN;
    public javax.swing.JPanel changeIedTAB;
    public static javax.swing.JButton changeValuesBTN;
    public static javax.swing.JPanel connectTAB;
    public static javax.swing.JLabel connectedLBL;
    public static javax.swing.JComboBox<String> createDatasetFcCB;
    public static javax.swing.JTextField createDatasetNumberOfEntriesTB;
    public static javax.swing.JRadioButton createDatasetRB;
    public static javax.swing.JTextField createDatasetRefTB;
    public static javax.swing.ButtonGroup datasetBG;
    public static javax.swing.JPanel datasetPNL;
    public static javax.swing.JRadioButton deleteDatasetRB;
    public static javax.swing.JRadioButton disableReportRB;
    public static javax.swing.JRadioButton enableReportRB;
    public static javax.swing.JPanel fcDatasetPNL;
    public static javax.swing.JLabel icodersclLBL;
    public static javax.swing.JTextField iedPathTB;
    public static javax.swing.JTextField integrityPeriodTB;
    public static javax.swing.JTextField ipTB;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel25;
    public static javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel10;
    public static javax.swing.JPanel jPanel12;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel7;
    public static javax.swing.JPanel jPanel8;
    public static javax.swing.JPanel jPanel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JSplitPane jSplitPane1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTabbedPane jTabbedPane4;
    public static javax.swing.JPanel logTAB;
    public static javax.swing.JTabbedPane mainFrame;
    public static javax.swing.JTextArea masterLogTA;
    public static javax.swing.JTextArea netDevicesTA;
    public static javax.swing.JTextArea netInfosTA;
    public static javax.swing.JPanel networkPNL;
    public static javax.swing.JPanel numberOfEntriesDatasetPNL;
    public static javax.swing.JTextField portTB;
    public static javax.swing.JPanel radioButtonsReportPNL;
    public static javax.swing.JPanel referenceDatasetPNL;
    public static javax.swing.JLabel referenceLBL;
    public static javax.swing.JPanel referenceReportPNL;
    public static javax.swing.JTextField referenceTB;
    public static javax.swing.ButtonGroup reportBG;
    public static javax.swing.JTextArea reportDatasetTA;
    public static javax.swing.JPanel reportPNL;
    public static javax.swing.JButton reportStartBTN;
    public static javax.swing.JRadioButton reserveReportRB;
    public static javax.swing.JLabel reserveTimeLBL;
    public static javax.swing.JPanel reserveTimeReportPNL;
    public static javax.swing.JTextField reserveTimeTB;
    public static javax.swing.JToggleButton saveCsvBTN;
    public static javax.swing.JButton selectFileBTN;
    public static javax.swing.JButton selectReferenceDatasetBTN;
    public static javax.swing.JButton selectReferencePulsBTN;
    public static javax.swing.JButton selectReferenceRampBTN;
    public static javax.swing.JButton selectReferenceReportBTN;
    public static javax.swing.JLabel selectedIedLBL;
    public static javax.swing.JRadioButton sendGeneralInterrogationReportRB;
    public static javax.swing.JRadioButton setDatasetReportRB;
    public static javax.swing.JRadioButton setIntegrityReportRB;
    public static javax.swing.JRadioButton setTriggerReportRB;
    public static javax.swing.JTextArea simLogTA;
    public static javax.swing.JComboBox<String> simulatePulsFcCB;
    public static javax.swing.JTextField simulatePulsMaxTB;
    public static javax.swing.JTextField simulatePulsMinTB;
    public static javax.swing.JTextField simulatePulsReferenceTB;
    public static javax.swing.JToggleButton simulatePulsStartBTN;
    public static javax.swing.JButton simulatePulsStopBTN;
    public static javax.swing.JTextField simulatePulsTimeOffTB;
    public static javax.swing.JTextField simulatePulsTimeOnTB;
    public static javax.swing.JComboBox<String> simulateRampFcCB;
    public static javax.swing.JTextField simulateRampFromTB;
    public static javax.swing.JTextField simulateRampReferenceTB;
    public static javax.swing.JButton simulateRampStartBTN;
    public static javax.swing.JTextField simulateRampStepsTB;
    public static javax.swing.JTextField simulateRampTimeTB;
    public static javax.swing.JTextField simulateRampToTB;
    public javax.swing.JPanel simulateTAB;
    public static javax.swing.JButton startBTN;
    public static javax.swing.JButton startDatasetBTN;
    public static javax.swing.JButton stopBTN;
    public static javax.swing.JLabel triggerOptionsLBL;
    public static javax.swing.JPanel triggerOptionsReportPNL;
    public static javax.swing.JTextField triggerOptionsTB;
    public static javax.swing.JLabel valueLBL;
    public static javax.swing.JPanel valueReportPNL;
    public static javax.swing.JTextField valueTB;
    // End of variables declaration//GEN-END:variables
}
